# Site settings
title: R(adiant) news
email: radiant@rady.ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  News about Radiant:  A platform-independent browser-based interface for business analytics in R, based on the Shiny package.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://vnijs.github.io" # the base hostname & protocol for your site
twitter_username: vrnijs
github_username:  vnijs
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
